/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDepositRouteImport } from './routes/_authenticated/deposit'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedReferralRouteImport } from './routes/_authenticated/referral'
import { Route as AuthenticatedWithdrawRouteImport } from './routes/_authenticated/withdraw'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedInvestIndexRouteImport } from './routes/_authenticated/invest.index'
import { Route as AuthenticatedInvestDetailsRouteImport } from './routes/_authenticated/invest.details'
import { Route as AuthenticatedInvestSuccessRouteImport } from './routes/_authenticated/invest.success'
import { Route as AuthenticatedInvestmentsIndexRouteImport } from './routes/_authenticated/investments.index'
import { Route as AuthenticatedInvestmentsHistoryRouteImport } from './routes/_authenticated/investments.history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDepositRoute = AuthenticatedDepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralRoute = AuthenticatedReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWithdrawRoute = AuthenticatedWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedInvestIndexRoute =
  AuthenticatedInvestIndexRouteImport.update({
    id: '/invest/',
    path: '/invest/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestDetailsRoute =
  AuthenticatedInvestDetailsRouteImport.update({
    id: '/invest/details',
    path: '/invest/details',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestSuccessRoute =
  AuthenticatedInvestSuccessRouteImport.update({
    id: '/invest/success',
    path: '/invest/success',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestmentsIndexRoute =
  AuthenticatedInvestmentsIndexRouteImport.update({
    id: '/investments/',
    path: '/investments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestmentsHistoryRoute =
  AuthenticatedInvestmentsHistoryRouteImport.update({
    id: '/investments/history',
    path: '/investments/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deposit': typeof AuthenticatedDepositRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referral': typeof AuthenticatedReferralRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invest/details': typeof AuthenticatedInvestDetailsRoute
  '/invest/success': typeof AuthenticatedInvestSuccessRoute
  '/investments/history': typeof AuthenticatedInvestmentsHistoryRoute
  '/invest/': typeof AuthenticatedInvestIndexRoute
  '/investments/': typeof AuthenticatedInvestmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deposit': typeof AuthenticatedDepositRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referral': typeof AuthenticatedReferralRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/invest/details': typeof AuthenticatedInvestDetailsRoute
  '/invest/success': typeof AuthenticatedInvestSuccessRoute
  '/investments/history': typeof AuthenticatedInvestmentsHistoryRoute
  '/invest': typeof AuthenticatedInvestIndexRoute
  '/investments': typeof AuthenticatedInvestmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deposit': typeof AuthenticatedDepositRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/referral': typeof AuthenticatedReferralRoute
  '/_authenticated/withdraw': typeof AuthenticatedWithdrawRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/invest/details': typeof AuthenticatedInvestDetailsRoute
  '/_authenticated/invest/success': typeof AuthenticatedInvestSuccessRoute
  '/_authenticated/investments/history': typeof AuthenticatedInvestmentsHistoryRoute
  '/_authenticated/invest/': typeof AuthenticatedInvestIndexRoute
  '/_authenticated/investments/': typeof AuthenticatedInvestmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/dashboard'
    | '/deposit'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/referral'
    | '/withdraw'
    | '/auth/callback'
    | '/invest/details'
    | '/invest/success'
    | '/investments/history'
    | '/invest/'
    | '/investments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/dashboard'
    | '/deposit'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/referral'
    | '/withdraw'
    | '/auth/callback'
    | '/invest/details'
    | '/invest/success'
    | '/investments/history'
    | '/invest'
    | '/investments'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/_authenticated/dashboard'
    | '/_authenticated/deposit'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/referral'
    | '/_authenticated/withdraw'
    | '/auth/callback'
    | '/_authenticated/invest/details'
    | '/_authenticated/invest/success'
    | '/_authenticated/investments/history'
    | '/_authenticated/invest/'
    | '/_authenticated/investments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deposit': {
      id: '/_authenticated/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof AuthenticatedDepositRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referral': {
      id: '/_authenticated/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof AuthenticatedReferralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/withdraw': {
      id: '/_authenticated/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AuthenticatedWithdrawRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/invest/': {
      id: '/_authenticated/invest/'
      path: '/invest'
      fullPath: '/invest/'
      preLoaderRoute: typeof AuthenticatedInvestIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invest/details': {
      id: '/_authenticated/invest/details'
      path: '/invest/details'
      fullPath: '/invest/details'
      preLoaderRoute: typeof AuthenticatedInvestDetailsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invest/success': {
      id: '/_authenticated/invest/success'
      path: '/invest/success'
      fullPath: '/invest/success'
      preLoaderRoute: typeof AuthenticatedInvestSuccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investments/': {
      id: '/_authenticated/investments/'
      path: '/investments'
      fullPath: '/investments/'
      preLoaderRoute: typeof AuthenticatedInvestmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investments/history': {
      id: '/_authenticated/investments/history'
      path: '/investments/history'
      fullPath: '/investments/history'
      preLoaderRoute: typeof AuthenticatedInvestmentsHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepositRoute: typeof AuthenticatedDepositRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReferralRoute: typeof AuthenticatedReferralRoute
  AuthenticatedWithdrawRoute: typeof AuthenticatedWithdrawRoute
  AuthenticatedInvestDetailsRoute: typeof AuthenticatedInvestDetailsRoute
  AuthenticatedInvestSuccessRoute: typeof AuthenticatedInvestSuccessRoute
  AuthenticatedInvestmentsHistoryRoute: typeof AuthenticatedInvestmentsHistoryRoute
  AuthenticatedInvestIndexRoute: typeof AuthenticatedInvestIndexRoute
  AuthenticatedInvestmentsIndexRoute: typeof AuthenticatedInvestmentsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepositRoute: AuthenticatedDepositRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReferralRoute: AuthenticatedReferralRoute,
  AuthenticatedWithdrawRoute: AuthenticatedWithdrawRoute,
  AuthenticatedInvestDetailsRoute: AuthenticatedInvestDetailsRoute,
  AuthenticatedInvestSuccessRoute: AuthenticatedInvestSuccessRoute,
  AuthenticatedInvestmentsHistoryRoute: AuthenticatedInvestmentsHistoryRoute,
  AuthenticatedInvestIndexRoute: AuthenticatedInvestIndexRoute,
  AuthenticatedInvestmentsIndexRoute: AuthenticatedInvestmentsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
