/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedReferralRouteImport } from './routes/_authenticated/referral'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedDepositIndexRouteImport } from './routes/_authenticated/deposit/index'
import { Route as AuthenticatedDepositCallbackRouteImport } from './routes/_authenticated/deposit/callback'
import { Route as AuthenticatedDepositSuccessRouteImport } from './routes/_authenticated/deposit/success'
import { Route as AuthenticatedInvestIndexRouteImport } from './routes/_authenticated/invest.index'
import { Route as AuthenticatedInvestDetailsRouteImport } from './routes/_authenticated/invest.details'
import { Route as AuthenticatedInvestSuccessRouteImport } from './routes/_authenticated/invest.success'
import { Route as AuthenticatedInvestmentsIndexRouteImport } from './routes/_authenticated/investments.index'
import { Route as AuthenticatedInvestmentsHistoryRouteImport } from './routes/_authenticated/investments.history'
import { Route as AuthenticatedProfileKycRouteImport } from './routes/_authenticated/profile.kyc'
import { Route as AuthenticatedProfilePasswordRouteImport } from './routes/_authenticated/profile.password'
import { Route as AuthenticatedProfilePersonalRouteImport } from './routes/_authenticated/profile.personal'
import { Route as AuthenticatedProfileStatementRouteImport } from './routes/_authenticated/profile.statement'
import { Route as AuthenticatedProfileTransactionsRouteImport } from './routes/_authenticated/profile.transactions'
import { Route as AuthenticatedWithdrawIndexRouteImport } from './routes/_authenticated/withdraw.index'
import { Route as AuthenticatedWithdrawMethodRouteImport } from './routes/_authenticated/withdraw.method'
import { Route as ApiPaystackWebhookRouteImport } from './routes/api/paystack/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralRoute = AuthenticatedReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDepositIndexRoute =
  AuthenticatedDepositIndexRouteImport.update({
    id: '/deposit/',
    path: '/deposit/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDepositCallbackRoute =
  AuthenticatedDepositCallbackRouteImport.update({
    id: '/deposit/callback',
    path: '/deposit/callback',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDepositSuccessRoute =
  AuthenticatedDepositSuccessRouteImport.update({
    id: '/deposit/success',
    path: '/deposit/success',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestIndexRoute =
  AuthenticatedInvestIndexRouteImport.update({
    id: '/invest/',
    path: '/invest/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestDetailsRoute =
  AuthenticatedInvestDetailsRouteImport.update({
    id: '/invest/details',
    path: '/invest/details',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestSuccessRoute =
  AuthenticatedInvestSuccessRouteImport.update({
    id: '/invest/success',
    path: '/invest/success',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestmentsIndexRoute =
  AuthenticatedInvestmentsIndexRouteImport.update({
    id: '/investments/',
    path: '/investments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestmentsHistoryRoute =
  AuthenticatedInvestmentsHistoryRouteImport.update({
    id: '/investments/history',
    path: '/investments/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileKycRoute = AuthenticatedProfileKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AuthenticatedProfileRoute,
} as any)
const AuthenticatedProfilePasswordRoute =
  AuthenticatedProfilePasswordRouteImport.update({
    id: '/password',
    path: '/password',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfilePersonalRoute =
  AuthenticatedProfilePersonalRouteImport.update({
    id: '/personal',
    path: '/personal',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileStatementRoute =
  AuthenticatedProfileStatementRouteImport.update({
    id: '/statement',
    path: '/statement',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileTransactionsRoute =
  AuthenticatedProfileTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedWithdrawIndexRoute =
  AuthenticatedWithdrawIndexRouteImport.update({
    id: '/withdraw/',
    path: '/withdraw/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWithdrawMethodRoute =
  AuthenticatedWithdrawMethodRouteImport.update({
    id: '/withdraw/method',
    path: '/withdraw/method',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPaystackWebhookRoute = ApiPaystackWebhookRouteImport.update({
  id: '/api/paystack/webhook',
  path: '/api/paystack/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/referral': typeof AuthenticatedReferralRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/deposit/callback': typeof AuthenticatedDepositCallbackRoute
  '/deposit/success': typeof AuthenticatedDepositSuccessRoute
  '/invest/details': typeof AuthenticatedInvestDetailsRoute
  '/invest/success': typeof AuthenticatedInvestSuccessRoute
  '/investments/history': typeof AuthenticatedInvestmentsHistoryRoute
  '/profile/kyc': typeof AuthenticatedProfileKycRoute
  '/profile/password': typeof AuthenticatedProfilePasswordRoute
  '/profile/personal': typeof AuthenticatedProfilePersonalRoute
  '/profile/statement': typeof AuthenticatedProfileStatementRoute
  '/profile/transactions': typeof AuthenticatedProfileTransactionsRoute
  '/withdraw/method': typeof AuthenticatedWithdrawMethodRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
  '/deposit/': typeof AuthenticatedDepositIndexRoute
  '/invest/': typeof AuthenticatedInvestIndexRoute
  '/investments/': typeof AuthenticatedInvestmentsIndexRoute
  '/withdraw/': typeof AuthenticatedWithdrawIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/referral': typeof AuthenticatedReferralRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/deposit/callback': typeof AuthenticatedDepositCallbackRoute
  '/deposit/success': typeof AuthenticatedDepositSuccessRoute
  '/invest/details': typeof AuthenticatedInvestDetailsRoute
  '/invest/success': typeof AuthenticatedInvestSuccessRoute
  '/investments/history': typeof AuthenticatedInvestmentsHistoryRoute
  '/profile/kyc': typeof AuthenticatedProfileKycRoute
  '/profile/password': typeof AuthenticatedProfilePasswordRoute
  '/profile/personal': typeof AuthenticatedProfilePersonalRoute
  '/profile/statement': typeof AuthenticatedProfileStatementRoute
  '/profile/transactions': typeof AuthenticatedProfileTransactionsRoute
  '/withdraw/method': typeof AuthenticatedWithdrawMethodRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
  '/deposit': typeof AuthenticatedDepositIndexRoute
  '/invest': typeof AuthenticatedInvestIndexRoute
  '/investments': typeof AuthenticatedInvestmentsIndexRoute
  '/withdraw': typeof AuthenticatedWithdrawIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/_authenticated/referral': typeof AuthenticatedReferralRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/deposit/callback': typeof AuthenticatedDepositCallbackRoute
  '/_authenticated/deposit/success': typeof AuthenticatedDepositSuccessRoute
  '/_authenticated/invest/details': typeof AuthenticatedInvestDetailsRoute
  '/_authenticated/invest/success': typeof AuthenticatedInvestSuccessRoute
  '/_authenticated/investments/history': typeof AuthenticatedInvestmentsHistoryRoute
  '/_authenticated/profile/kyc': typeof AuthenticatedProfileKycRoute
  '/_authenticated/profile/password': typeof AuthenticatedProfilePasswordRoute
  '/_authenticated/profile/personal': typeof AuthenticatedProfilePersonalRoute
  '/_authenticated/profile/statement': typeof AuthenticatedProfileStatementRoute
  '/_authenticated/profile/transactions': typeof AuthenticatedProfileTransactionsRoute
  '/_authenticated/withdraw/method': typeof AuthenticatedWithdrawMethodRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
  '/_authenticated/deposit/': typeof AuthenticatedDepositIndexRoute
  '/_authenticated/invest/': typeof AuthenticatedInvestIndexRoute
  '/_authenticated/investments/': typeof AuthenticatedInvestmentsIndexRoute
  '/_authenticated/withdraw/': typeof AuthenticatedWithdrawIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/dashboard'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/referral'
    | '/auth/callback'
    | '/deposit/callback'
    | '/deposit/success'
    | '/invest/details'
    | '/invest/success'
    | '/investments/history'
    | '/profile/kyc'
    | '/profile/password'
    | '/profile/personal'
    | '/profile/statement'
    | '/profile/transactions'
    | '/withdraw/method'
    | '/api/paystack/webhook'
    | '/deposit/'
    | '/invest/'
    | '/investments/'
    | '/withdraw/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/dashboard'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/referral'
    | '/auth/callback'
    | '/deposit/callback'
    | '/deposit/success'
    | '/invest/details'
    | '/invest/success'
    | '/investments/history'
    | '/profile/kyc'
    | '/profile/password'
    | '/profile/personal'
    | '/profile/statement'
    | '/profile/transactions'
    | '/withdraw/method'
    | '/api/paystack/webhook'
    | '/deposit'
    | '/invest'
    | '/investments'
    | '/withdraw'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/referral'
    | '/auth/callback'
    | '/_authenticated/deposit/callback'
    | '/_authenticated/deposit/success'
    | '/_authenticated/invest/details'
    | '/_authenticated/invest/success'
    | '/_authenticated/investments/history'
    | '/_authenticated/profile/kyc'
    | '/_authenticated/profile/password'
    | '/_authenticated/profile/personal'
    | '/_authenticated/profile/statement'
    | '/_authenticated/profile/transactions'
    | '/_authenticated/withdraw/method'
    | '/api/paystack/webhook'
    | '/_authenticated/deposit/'
    | '/_authenticated/invest/'
    | '/_authenticated/investments/'
    | '/_authenticated/withdraw/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiPaystackWebhookRoute: typeof ApiPaystackWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referral': {
      id: '/_authenticated/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof AuthenticatedReferralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/deposit/': {
      id: '/_authenticated/deposit/'
      path: '/deposit'
      fullPath: '/deposit/'
      preLoaderRoute: typeof AuthenticatedDepositIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deposit/callback': {
      id: '/_authenticated/deposit/callback'
      path: '/deposit/callback'
      fullPath: '/deposit/callback'
      preLoaderRoute: typeof AuthenticatedDepositCallbackRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deposit/success': {
      id: '/_authenticated/deposit/success'
      path: '/deposit/success'
      fullPath: '/deposit/success'
      preLoaderRoute: typeof AuthenticatedDepositSuccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invest/': {
      id: '/_authenticated/invest/'
      path: '/invest'
      fullPath: '/invest/'
      preLoaderRoute: typeof AuthenticatedInvestIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invest/details': {
      id: '/_authenticated/invest/details'
      path: '/invest/details'
      fullPath: '/invest/details'
      preLoaderRoute: typeof AuthenticatedInvestDetailsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invest/success': {
      id: '/_authenticated/invest/success'
      path: '/invest/success'
      fullPath: '/invest/success'
      preLoaderRoute: typeof AuthenticatedInvestSuccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investments/': {
      id: '/_authenticated/investments/'
      path: '/investments'
      fullPath: '/investments/'
      preLoaderRoute: typeof AuthenticatedInvestmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investments/history': {
      id: '/_authenticated/investments/history'
      path: '/investments/history'
      fullPath: '/investments/history'
      preLoaderRoute: typeof AuthenticatedInvestmentsHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/kyc': {
      id: '/_authenticated/profile/kyc'
      path: '/kyc'
      fullPath: '/profile/kyc'
      preLoaderRoute: typeof AuthenticatedProfileKycRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/password': {
      id: '/_authenticated/profile/password'
      path: '/password'
      fullPath: '/profile/password'
      preLoaderRoute: typeof AuthenticatedProfilePasswordRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/personal': {
      id: '/_authenticated/profile/personal'
      path: '/personal'
      fullPath: '/profile/personal'
      preLoaderRoute: typeof AuthenticatedProfilePersonalRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/statement': {
      id: '/_authenticated/profile/statement'
      path: '/statement'
      fullPath: '/profile/statement'
      preLoaderRoute: typeof AuthenticatedProfileStatementRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/transactions': {
      id: '/_authenticated/profile/transactions'
      path: '/transactions'
      fullPath: '/profile/transactions'
      preLoaderRoute: typeof AuthenticatedProfileTransactionsRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/withdraw/': {
      id: '/_authenticated/withdraw/'
      path: '/withdraw'
      fullPath: '/withdraw/'
      preLoaderRoute: typeof AuthenticatedWithdrawIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/withdraw/method': {
      id: '/_authenticated/withdraw/method'
      path: '/withdraw/method'
      fullPath: '/withdraw/method'
      preLoaderRoute: typeof AuthenticatedWithdrawMethodRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/paystack/webhook': {
      id: '/api/paystack/webhook'
      path: '/api/paystack/webhook'
      fullPath: '/api/paystack/webhook'
      preLoaderRoute: typeof ApiPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileKycRoute: typeof AuthenticatedProfileKycRoute
  AuthenticatedProfilePasswordRoute: typeof AuthenticatedProfilePasswordRoute
  AuthenticatedProfilePersonalRoute: typeof AuthenticatedProfilePersonalRoute
  AuthenticatedProfileStatementRoute: typeof AuthenticatedProfileStatementRoute
  AuthenticatedProfileTransactionsRoute: typeof AuthenticatedProfileTransactionsRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileKycRoute: AuthenticatedProfileKycRoute,
  AuthenticatedProfilePasswordRoute: AuthenticatedProfilePasswordRoute,
  AuthenticatedProfilePersonalRoute: AuthenticatedProfilePersonalRoute,
  AuthenticatedProfileStatementRoute: AuthenticatedProfileStatementRoute,
  AuthenticatedProfileTransactionsRoute: AuthenticatedProfileTransactionsRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedReferralRoute: typeof AuthenticatedReferralRoute
  AuthenticatedDepositCallbackRoute: typeof AuthenticatedDepositCallbackRoute
  AuthenticatedDepositSuccessRoute: typeof AuthenticatedDepositSuccessRoute
  AuthenticatedInvestDetailsRoute: typeof AuthenticatedInvestDetailsRoute
  AuthenticatedInvestSuccessRoute: typeof AuthenticatedInvestSuccessRoute
  AuthenticatedInvestmentsHistoryRoute: typeof AuthenticatedInvestmentsHistoryRoute
  AuthenticatedWithdrawMethodRoute: typeof AuthenticatedWithdrawMethodRoute
  AuthenticatedDepositIndexRoute: typeof AuthenticatedDepositIndexRoute
  AuthenticatedInvestIndexRoute: typeof AuthenticatedInvestIndexRoute
  AuthenticatedInvestmentsIndexRoute: typeof AuthenticatedInvestmentsIndexRoute
  AuthenticatedWithdrawIndexRoute: typeof AuthenticatedWithdrawIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedReferralRoute: AuthenticatedReferralRoute,
  AuthenticatedDepositCallbackRoute: AuthenticatedDepositCallbackRoute,
  AuthenticatedDepositSuccessRoute: AuthenticatedDepositSuccessRoute,
  AuthenticatedInvestDetailsRoute: AuthenticatedInvestDetailsRoute,
  AuthenticatedInvestSuccessRoute: AuthenticatedInvestSuccessRoute,
  AuthenticatedInvestmentsHistoryRoute: AuthenticatedInvestmentsHistoryRoute,
  AuthenticatedWithdrawMethodRoute: AuthenticatedWithdrawMethodRoute,
  AuthenticatedDepositIndexRoute: AuthenticatedDepositIndexRoute,
  AuthenticatedInvestIndexRoute: AuthenticatedInvestIndexRoute,
  AuthenticatedInvestmentsIndexRoute: AuthenticatedInvestmentsIndexRoute,
  AuthenticatedWithdrawIndexRoute: AuthenticatedWithdrawIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiPaystackWebhookRoute: ApiPaystackWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
